-- MySQL Script generated by MySQL Workbench
-- 12/27/15 20:09:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crud_oo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_oo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_oo` DEFAULT CHARACTER SET utf8 ;
USE `crud_oo` ;

-- -----------------------------------------------------
-- Table `crud_oo`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_oo`.`produto` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `unidade` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`produto_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
